# Phase 1 — Gemini Pro Annotation (V1 Baseline Dataset)

**Thesis chapter:** Chapter 3 — Model Development (V1 Baseline)

This notebook generates the first labeled dataset for IMRaD move classification.  
The **264,799-sentence** unarXive corpus is processed chunk-by-chunk through Gemini Pro  
using a minimal 3-class prompt that assigns each sentence to one of:

| Label | Move |
|---|---|
| Establishing a Research Territory | Move 0 |
| Establishing a Niche | Move 1 |
| Occupying the Niche | Move 2 |

Results are saved to Google Drive as CSV chunks and later used to fine-tune the V1 BERT model.  
> **Outcome:** ~264 K annotated sentences — quality limited by the simple prompt, leading to 44.61 % BERT accuracy (Chapter 3).

## 1 — Setup
Mount Google Drive and install dependencies.

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/pfe/introductions_training.csv')

## 2 — Dataset Overview
Load the full unarXive introduction corpus (264,799 rows).

In [3]:
df.head()

   Unnamed: 0                                               text
0           0  Food recommendation has become an essential me...
1           1  We introduce and discuss the FEO that extends ...
2           9  Photolithography is one of the most important ...
3          10  With the technological development of the semi...
4          11  To further improve the performance of SMC, fra...

In [4]:
df.shape

(264799, 2)

## 3 — Chunking
Split the corpus into 1,000-row CSV chunks for incremental processing. Each chunk is saved to `/pfe/introductions_chunks/`.

In [5]:
from google.colab import drive
import pandas as pd


for i in range(0, df.shape[0], 1000):
  df_subset = df.iloc[i:i+1000]
  filename = f"/content/drive/MyDrive/pfe/introductions_chunks/introductions_training_{i}.csv"
  df_subset.to_csv(filename, index=False)

In [6]:
import pandas as pd
df_0 = pd.read_csv('/content/drive/MyDrive/pfe/introductions_chunks/introductions_training_0.csv')

In [7]:
df_0.head()

   Unnamed: 0                                               text
0           0  Food recommendation has become an essential me...
1           1  We introduce and discuss the FEO that extends ...
2           9  Photolithography is one of the most important ...
3          10  With the technological development of the semi...
4          11  To further improve the performance of SMC, fra...

## 4 — V1 Annotation Prompt
Define the Gemini Pro model and the V1 prompt. The prompt is intentionally minimal — it names the three moves but provides no examples or sub-move definitions. This limitation is addressed in V2.

In [8]:
import time
import google.generativeai as genai
genai.configure(api_key="YOUR_API_KEY_HERE")

In [9]:
introduction = """

Electronic cigarettes (also known as vapes, vaporizers, or vape pens) were introduced into the US market in 2007. They are generally battery-powered products that heat liquid into an aerosol that is inhaled by the user. These devices are designed to deliver nicotine and flavors; they also contain chemicals such as propylene glycol, glycerin, and many other constituents. Use of e-cigarettes has dramatically increased over the past 4 years, tripling among high school students from a rate of 4.5% in 2011 to 27.4% in 2014 (CDC, 2015, 2016). Further, 27.4% of adolescents in the U.S. have ever used e-cigarettes (CDC, 2015), with 30% of California youth reporting ever using an e-cigarette (California Department of Public Health, 2015)…

The literature on e-cigarette attitudes thus far has predominantly focused on harm perceptions and general acceptability of and attitudes towards e-cigarettes and cigarettes. To our knowledge, there are few studies that have more comprehensively examined adolescents' specific attitudes towards and knowledge about e-cigarettes, and/or whether such attitudes differ between those who have and have not used e-cigarettes or other tobacco...

We thus examined a broad array of adolescents' knowledge and attitudes regarding e-cigarette ingredients, addictive properties, safety, cessation, perceived prevalence, accessibility, price, and regulation. We also examined whether these attitudes differ between adolescents who have and have not used cigarettes and/or e-cigarettes. Based on the small body of literature on e-cigarette attitudes, the larger set of literature on adolescents' attitudes towards cigarettes, and the relationship between such attitudes and tobacco use (e.g., Halpern-Felsher et al., 2004; Krosnick et al., 2006; Song et al., 2009; Roditis et al., 2016), we hypothesized that: (1) adolescents will believe that a greater number of parents, siblings, and peers are using e-cigarettes compared to cigarettes; (2)...


"""

In [10]:
import nltk
nltk.download('punkt')
sentences = nltk.sent_tokenize(introduction)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [11]:
sentences[0]

'\n\nElectronic cigarettes (also known as vapes, vaporizers, or vape pens) were introduced into the US market in 2007.'

In [12]:
chunk=sentences[3]

'Establishing a Research Territory'

In [14]:
import pandas as pd
chunk_id = 2000
df = pd.read_csv(f'/content/drive/MyDrive/pfe/introductions_chunks/introductions_training_{chunk_id}.csv')

In [15]:
df.head()

   Unnamed: 0                                               text
0        4053  Real estate pricing is often qualitative, and ...
1        4069  Causal modeling is a crucial tool to represent...
2        4070  Within causal modeling, there is a recent grow...
3        4071  In this paper, we extend previous work on \(\t...
4        4074  Machine learning algorithms have shown promise...

In [16]:
df.shape

(1000, 2)

## 5 — Sentence-Level Annotation Loop
For each row in the current chunk, tokenize the introduction into sentences (NLTK), call Gemini, and append the result to `results`. Progress is logged after each sentence.

In [17]:
model = genai.GenerativeModel('gemini-pro')

In [18]:
def analyse_imrad_sentence(sentence):
  prompt_moves = f"Analyze the provided text {sentence}, which represents a sentence of an introduction of an IMRaD formatted scientific paper . Classify the sentence into an imrad introduction move , knowing that the IMRaD moves are:(Establishing a Research Territory , Establishing a Niche , Occupying the Niche.). the output should be the correspending imarad move without anything extra"
  # Generate response from Gemini to extract moves
  time.sleep(0.2)



  try:
    completion_moves = model.generate_content(prompt_moves)
    return completion_moves.text
  except:
     pass
  return None

In [19]:
import time
import pandas as pd
results = []
row_id = 411
column_id = 0
def analyze_imrad_introduction(introduction,df_id,introduction_index):
  sentences = nltk.sent_tokenize(introduction)
  for i, sentence in enumerate(sentences):
    if(row_id == introduction_index and i <= column_id) or ( len(sentence)== 0 ):
      continue
    start = time.time()
    print(f"----------sentence {i}")
    result = analyse_imrad_sentence(sentence)

    end = time.time()

    print(f"-------Total time elapsed: {end - start}")
    results.append({'df_id':df_id,'introduction_id': introduction_index, 'sentence': sentence, 'label': result})
  return len(sentences)

In [20]:
start = time.time()
for index, row in df.iterrows():
  # Extract the sentence from the current row
  if index <= row_id:
    continue
  introduction = row['text']
  print(f"Processed {index} rows out of {df.shape[0]} ------------------")


  # Analyze the sentence using the function

  sentences_length = analyze_imrad_introduction(introduction,chunk_id,index)

  # Log progress every 100 rows


  print(f"Processed {index} rows out of {df.shape[0]} total sentences {sentences_length}")


end = time.time()

print(f"Total time elapsed: {end - start}")

Processed 412 rows out of 1000 ------------------
----------sentence 0
... [56 lines truncated] ...
-------Total time elapsed: 1.8785769939422607
----------sentence 1

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1069.68ms

-------Total time elapsed: 1.2725579738616943
----------sentence 2
... [56 lines truncated] ...
-------Total time elapsed: 1.649172067642212
----------sentence 1

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1043.31ms

-------Total time elapsed: 1.2470550537109375
----------sentence 2
... [48 lines truncated] ...
-------Total time elapsed: 2.1831517219543457
----------sentence 6

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1244.73ms

-------Total time elapsed: 1.4481027126312256
----------sentence 7
... [36 lines truncated] ...
Processed 432 rows out of 1000 ------------------
----------sentence 0

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1370.08ms

-------Total time elapsed: 1.5727641582489014
----------sentence 1
... [16 lines truncated] ...
-------Total time elapsed: 3.243422508239746
----------sentence 3

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1088.95ms

-------Total time elapsed: 1.2952196598052979
----------sentence 4
... [56 lines truncated] ...
-------Total time elapsed: 1.6748449802398682
----------sentence 3

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1243.85ms

-------Total time elapsed: 1.4474925994873047
----------sentence 4
... [56 lines truncated] ...
Processed 449 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1014.88ms

-------Total time elapsed: 1.21907377243042
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 737.50ms

-------Total time elapsed: 0.940462589263916
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 839.29ms

-------Total time elapsed: 1.0429933071136475
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 786.36ms

-------Total time elapsed: 0.991844654083252
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 815.34ms

-------Total time elapsed: 1.0179622173309326
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 762.21ms

-------Total time elapsed: 0.9662461280822754
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 863.96ms

-------Total time elapsed: 1.0675060749053955
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 837.09ms

-------Total time elapsed: 1.0426809787750244
----------sentence 8

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 890.46ms

-------Total time elapsed: 1.0932724475860596
----------sentence 9

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 761.88ms

-------Total time elapsed: 0.9655253887176514
----------sentence 10

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1039.87ms

-------Total time elapsed: 1.243535041809082
----------sentence 11

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 814.74ms

-------Total time elapsed: 1.0161731243133545
Processed 449 rows out of 1000 total sentences 12
Processed 450 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 965.82ms

-------Total time elapsed: 1.1682062149047852
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 888.12ms

-------Total time elapsed: 1.094311237335205
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1394.89ms

-------Total time elapsed: 1.5992801189422607
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 763.29ms

-------Total time elapsed: 0.9673950672149658
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 890.06ms

-------Total time elapsed: 1.09368896484375
Processed 450 rows out of 1000 total sentences 5
Processed 451 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 913.66ms

-------Total time elapsed: 1.1221497058868408
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 841.14ms

-------Total time elapsed: 1.0434613227844238
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 786.15ms

-------Total time elapsed: 0.9941809177398682
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 737.37ms

-------Total time elapsed: 0.9405479431152344
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 788.15ms

-------Total time elapsed: 0.9916441440582275
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 838.19ms

-------Total time elapsed: 1.0414373874664307
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 737.22ms

-------Total time elapsed: 0.9405889511108398
----------sentence 7
... [56 lines truncated] ...
-------Total time elapsed: 1.8542027473449707
----------sentence 4

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1165.39ms

-------Total time elapsed: 1.3720448017120361
----------sentence 5
... [34 lines truncated] ...
Processed 470 rows out of 1000 ------------------
----------sentence 0

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1091.48ms

-------Total time elapsed: 1.2940900325775146
----------sentence 1
... [44 lines truncated] ...
-------Total time elapsed: 1.7526895999908447
----------sentence 3

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 964.83ms

-------Total time elapsed: 1.1684274673461914
----------sentence 4
... [8 lines truncated] ...
-------Total time elapsed: 1.7546675205230713
----------sentence 3

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 990.02ms

-------Total time elapsed: 1.1962175369262695
----------sentence 4
... [24 lines truncated] ...
Processed 477 rows out of 1000 ------------------
----------sentence 0

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 991.45ms

-------Total time elapsed: 1.1946618556976318
----------sentence 1
... [18 lines truncated] ...
-------Total time elapsed: 1.8531465530395508
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 888.65ms

-------Total time elapsed: 1.0941126346588135
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 761.32ms

-------Total time elapsed: 0.9677071571350098
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 786.72ms

-------Total time elapsed: 0.9926140308380127
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 789.13ms

-------Total time elapsed: 0.9940898418426514
----------sentence 8

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 661.89ms

-------Total time elapsed: 0.8650333881378174
----------sentence 9

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 762.32ms

-------Total time elapsed: 0.9647657871246338
----------sentence 10

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 788.91ms

-------Total time elapsed: 0.9911201000213623
Processed 478 rows out of 1000 total sentences 11
Processed 479 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 711.35ms

-------Total time elapsed: 0.9157841205596924
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 765.02ms

-------Total time elapsed: 0.9670004844665527
Processed 479 rows out of 1000 total sentences 2
Processed 480 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 887.43ms

-------Total time elapsed: 1.0920863151550293
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 863.80ms

-------Total time elapsed: 1.0671148300170898
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 737.36ms

-------Total time elapsed: 0.9409794807434082
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 838.06ms

-------Total time elapsed: 1.0418128967285156
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 964.48ms

-------Total time elapsed: 1.1677165031433105
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 863.93ms

-------Total time elapsed: 1.0672359466552734
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1118.66ms

-------Total time elapsed: 1.3211908340454102
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 739.91ms

-------Total time elapsed: 0.9420638084411621
Processed 480 rows out of 1000 total sentences 8
Processed 481 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.71ms

-------Total time elapsed: 1.0172762870788574
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 812.75ms

-------Total time elapsed: 1.0172653198242188
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 738.75ms

-------Total time elapsed: 0.9414329528808594
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 892.31ms

-------Total time elapsed: 1.09324049949646
Processed 481 rows out of 1000 total sentences 4
Processed 482 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 862.67ms

-------Total time elapsed: 1.0682108402252197
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.71ms

-------Total time elapsed: 1.0164413452148438
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 788.10ms

-------Total time elapsed: 0.9912753105163574
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 711.05ms

-------Total time elapsed: 0.9151310920715332
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 838.03ms

-------Total time elapsed: 1.0414907932281494
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 915.89ms

-------Total time elapsed: 1.1189208030700684
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 739.04ms

-------Total time elapsed: 0.9408245086669922
Processed 482 rows out of 1000 total sentences 7
Processed 483 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 839.55ms

-------Total time elapsed: 1.0432870388031006
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 738.30ms

-------Total time elapsed: 0.9410929679870605
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 763.53ms

-------Total time elapsed: 0.9666574001312256
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 966.38ms

-------Total time elapsed: 1.1696937084197998
----------sentence 4
... [30 lines truncated] ...
-------Total time elapsed: 1.7263622283935547
----------sentence 1

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1067.63ms

-------Total time elapsed: 1.2700245380401611
----------sentence 2
... [40 lines truncated] ...
-------Total time elapsed: 1.724355936050415
----------sentence 1

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1270.39ms

-------Total time elapsed: 1.4751348495483398
----------sentence 2
... [56 lines truncated] ...
-------Total time elapsed: 2.1313631534576416
----------sentence 2

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1118.81ms

-------Total time elapsed: 1.3228528499603271
----------sentence 3
... [10 lines truncated] ...
-------Total time elapsed: 1.8775320053100586
----------sentence 9

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1196.24ms

-------Total time elapsed: 1.397383689880371
Processed 500 rows out of 1000 total sentences 10
... [26 lines truncated] ...
-------Total time elapsed: 1.9529614448547363
----------sentence 1

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 991.38ms

-------Total time elapsed: 1.194556474685669
----------sentence 2
... [48 lines truncated] ...
Processed 509 rows out of 1000 ------------------
----------sentence 0

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1114.58ms

-------Total time elapsed: 1.3225338459014893
----------sentence 1
... [46 lines truncated] ...
-------Total time elapsed: 1.8035666942596436
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1018.42ms

-------Total time elapsed: 1.2221262454986572
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 687.77ms

-------Total time elapsed: 0.8916575908660889
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 736.92ms

-------Total time elapsed: 0.9429357051849365
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 788.97ms

-------Total time elapsed: 0.9918782711029053
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 868.25ms

-------Total time elapsed: 1.0708715915679932
----------sentence 8

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 660.59ms

-------Total time elapsed: 0.8665306568145752
----------sentence 9

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 687.85ms

-------Total time elapsed: 0.8897898197174072
----------sentence 10

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 941.22ms

-------Total time elapsed: 1.143500804901123
Processed 513 rows out of 1000 total sentences 11
Processed 514 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 890.51ms

-------Total time elapsed: 1.0946505069732666
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 613.50ms

-------Total time elapsed: 0.8142452239990234
Processed 514 rows out of 1000 total sentences 2
Processed 515 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 786.45ms

-------Total time elapsed: 0.9926037788391113
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 761.37ms

-------Total time elapsed: 0.9652581214904785
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 762.67ms

-------Total time elapsed: 0.9658033847808838
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 788.48ms

-------Total time elapsed: 0.9923086166381836
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1066.44ms

-------Total time elapsed: 1.2697663307189941
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 940.18ms

-------Total time elapsed: 1.1439769268035889
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 864.90ms

-------Total time elapsed: 1.0685029029846191
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 890.90ms

-------Total time elapsed: 1.0932233333587646
Processed 515 rows out of 1000 total sentences 8
Processed 516 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 862.86ms

-------Total time elapsed: 1.0684068202972412
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.49ms

-------Total time elapsed: 1.0179827213287354
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1675.42ms

-------Total time elapsed: 1.879167079925537
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1571.57ms

-------Total time elapsed: 1.776595115661621
Processed 516 rows out of 1000 total sentences 4
Processed 517 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 913.91ms

-------Total time elapsed: 1.117201805114746
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 965.64ms

-------Total time elapsed: 1.169532299041748
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 840.32ms

-------Total time elapsed: 1.0428824424743652
----------sentence 3
... [56 lines truncated] ...
-------Total time elapsed: 3.47393536567688
----------sentence 45

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1318.88ms

-------Total time elapsed: 1.5229251384735107
----------sentence 46

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1623.48ms

-------Total time elapsed: 1.8276104927062988
----------sentence 47
... [4 lines truncated] ...
-------Total time elapsed: 1.9042458534240723
----------sentence 50

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1625.79ms

-------Total time elapsed: 1.828268051147461
----------sentence 51

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 811.12ms

-------Total time elapsed: 1.0170080661773682
----------sentence 52

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1141.96ms

-------Total time elapsed: 1.3452560901641846
----------sentence 53

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 865.24ms

-------Total time elapsed: 1.067983865737915
----------sentence 54

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 736.88ms

-------Total time elapsed: 0.9408235549926758
----------sentence 55

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.11ms

-------Total time elapsed: 1.0178349018096924
----------sentence 56

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 713.10ms

-------Total time elapsed: 0.9167976379394531
----------sentence 57

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 814.72ms

-------Total time elapsed: 1.0185818672180176
----------sentence 58

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 711.88ms

-------Total time elapsed: 0.9163169860839844
----------sentence 59

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 713.11ms

-------Total time elapsed: 0.9166173934936523
----------sentence 60

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 763.66ms

-------Total time elapsed: 0.966731071472168
----------sentence 61

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 661.14ms

-------Total time elapsed: 0.8655333518981934
----------sentence 62

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 662.39ms

-------Total time elapsed: 0.8650596141815186
----------sentence 63

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 839.00ms

-------Total time elapsed: 1.0444748401641846
----------sentence 64

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 863.70ms

-------Total time elapsed: 1.0665183067321777
----------sentence 65

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 965.37ms

-------Total time elapsed: 1.1681468486785889
----------sentence 66

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 864.67ms

-------Total time elapsed: 1.0685887336730957
----------sentence 67

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 915.87ms

-------Total time elapsed: 1.1187121868133545
----------sentence 68

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 939.92ms

-------Total time elapsed: 1.1446459293365479
----------sentence 69

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 940.95ms

-------Total time elapsed: 1.1440150737762451
----------sentence 70

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 814.57ms

-------Total time elapsed: 1.0175719261169434
----------sentence 71

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 764.77ms

-------Total time elapsed: 0.9676368236541748
----------sentence 72

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1371.51ms

-------Total time elapsed: 1.574742317199707
----------sentence 73

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 867.12ms

-------Total time elapsed: 1.0713486671447754
----------sentence 74
... [56 lines truncated] ...
-------Total time elapsed: 1.7009925842285156
----------sentence 222

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 911.59ms

-------Total time elapsed: 1.1175274848937988
----------sentence 223

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 787.09ms

-------Total time elapsed: 0.9920639991760254
----------sentence 224

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 865.38ms

-------Total time elapsed: 1.0680925846099854
----------sentence 225

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 791.46ms

-------Total time elapsed: 0.9953136444091797
----------sentence 226

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 737.91ms

-------Total time elapsed: 0.9415466785430908
----------sentence 227

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 687.23ms

-------Total time elapsed: 0.888993501663208
----------sentence 228

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 764.13ms

-------Total time elapsed: 0.9675910472869873
----------sentence 229

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 736.46ms

-------Total time elapsed: 0.9437885284423828
----------sentence 230

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 739.04ms

-------Total time elapsed: 0.9436421394348145
----------sentence 231

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 789.90ms

-------Total time elapsed: 0.9924848079681396
----------sentence 232

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 789.72ms

-------Total time elapsed: 0.9929203987121582
----------sentence 233

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 762.80ms

-------Total time elapsed: 0.9654796123504639
----------sentence 234

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 913.86ms

-------Total time elapsed: 1.1178772449493408
----------sentence 235

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 784.97ms

-------Total time elapsed: 0.989365816116333
----------sentence 236

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 735.30ms

-------Total time elapsed: 0.9406528472900391
----------sentence 237

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1040.86ms

-------Total time elapsed: 1.2467641830444336
----------sentence 238

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 712.35ms

-------Total time elapsed: 0.9151403903961182
----------sentence 239

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1015.73ms

-------Total time elapsed: 1.2190322875976562
----------sentence 240

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 713.04ms

-------Total time elapsed: 0.9155440330505371
----------sentence 241

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 662.81ms

-------Total time elapsed: 0.8655085563659668
----------sentence 242

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 790.76ms

-------Total time elapsed: 0.9937844276428223
----------sentence 243

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 788.77ms

-------Total time elapsed: 0.9920916557312012
----------sentence 244

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 663.40ms

-------Total time elapsed: 0.8662188053131104
----------sentence 245

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 664.05ms

-------Total time elapsed: 0.8676128387451172
----------sentence 246

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 735.68ms

-------Total time elapsed: 0.9388296604156494
----------sentence 247

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 863.53ms

-------Total time elapsed: 1.0655710697174072
----------sentence 248

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 762.08ms

-------Total time elapsed: 0.9661147594451904
----------sentence 249

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 763.67ms

-------Total time elapsed: 0.9661755561828613
----------sentence 250

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 687.66ms

-------Total time elapsed: 0.8902649879455566
----------sentence 251

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 738.98ms

-------Total time elapsed: 0.941864013671875
----------sentence 252

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 711.67ms

-------Total time elapsed: 0.9171321392059326
----------sentence 253

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 686.04ms

-------Total time elapsed: 0.8926994800567627
----------sentence 254
... [56 lines truncated] ...
-------Total time elapsed: 3.094877243041992
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 967.36ms

-------Total time elapsed: 1.1697211265563965
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 838.99ms

-------Total time elapsed: 1.0420165061950684
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1065.92ms

-------Total time elapsed: 1.269423484802246
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 868.29ms

-------Total time elapsed: 1.0725839138031006
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.58ms

-------Total time elapsed: 1.0164783000946045
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 915.42ms

-------Total time elapsed: 1.120032787322998
----------sentence 8

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 660.95ms

-------Total time elapsed: 0.8668868541717529
----------sentence 9

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 865.74ms

-------Total time elapsed: 1.0703084468841553
----------sentence 10

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 687.31ms

-------Total time elapsed: 0.8917257785797119
----------sentence 11

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 812.62ms

-------Total time elapsed: 1.0183284282684326
----------sentence 12

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 687.51ms

-------Total time elapsed: 0.8917129039764404
----------sentence 13

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.11ms

-------Total time elapsed: 1.0182387828826904
----------sentence 14

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 786.90ms

-------Total time elapsed: 0.992121696472168
----------sentence 15

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 838.48ms

-------Total time elapsed: 1.043100118637085
----------sentence 16

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 662.12ms

-------Total time elapsed: 0.8654756546020508
----------sentence 17

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 763.36ms

-------Total time elapsed: 0.9676816463470459
----------sentence 18

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1143.69ms

-------Total time elapsed: 1.3469228744506836
----------sentence 19

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 916.32ms

-------Total time elapsed: 1.117055892944336
Processed 535 rows out of 1000 total sentences 20
Processed 536 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 789.27ms

-------Total time elapsed: 0.9911563396453857
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 736.81ms

-------Total time elapsed: 0.942742109298706
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 712.15ms

-------Total time elapsed: 0.9157030582427979
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.67ms

-------Total time elapsed: 1.0161633491516113
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.93ms

-------Total time elapsed: 1.017101526260376
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 839.37ms

-------Total time elapsed: 1.0443060398101807
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 814.41ms

-------Total time elapsed: 1.0173039436340332
Processed 536 rows out of 1000 total sentences 7
Processed 537 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 839.69ms

-------Total time elapsed: 1.0415382385253906
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 738.26ms

-------Total time elapsed: 0.9420804977416992
Processed 537 rows out of 1000 total sentences 2
Processed 538 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 586.71ms

-------Total time elapsed: 0.790668249130249
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 762.36ms

-------Total time elapsed: 0.9654414653778076
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 736.46ms

-------Total time elapsed: 0.9388866424560547
----------sentence 3
... [56 lines truncated] ...
-------Total time elapsed: 1.8270304203033447
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 940.21ms

-------Total time elapsed: 1.1443541049957275
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1016.28ms

-------Total time elapsed: 1.220038890838623
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 941.73ms

-------Total time elapsed: 1.145047903060913
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 788.42ms

-------Total time elapsed: 0.9919252395629883
Processed 578 rows out of 1000 total sentences 5
Processed 579 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 836.94ms

-------Total time elapsed: 1.0432193279266357
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 634.80ms

-------Total time elapsed: 0.8404033184051514
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 814.24ms

-------Total time elapsed: 1.0173652172088623
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 665.62ms

-------Total time elapsed: 0.8679225444793701
Processed 579 rows out of 1000 total sentences 4
Processed 580 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 840.42ms

-------Total time elapsed: 1.0428776741027832
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 784.92ms

-------Total time elapsed: 0.9904448986053467
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 762.08ms

-------Total time elapsed: 0.9659321308135986
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 636.50ms

-------Total time elapsed: 0.8391232490539551
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 839.29ms

-------Total time elapsed: 1.0425443649291992
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 717.07ms

-------Total time elapsed: 0.9192376136779785
Processed 580 rows out of 1000 total sentences 6
Processed 581 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 684.98ms

-------Total time elapsed: 0.8902356624603271
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 687.43ms

-------Total time elapsed: 0.8903734683990479
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 761.84ms

-------Total time elapsed: 0.9682681560516357
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 813.99ms

-------Total time elapsed: 1.0176928043365479
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 839.78ms

-------Total time elapsed: 1.0431177616119385
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 791.07ms

-------Total time elapsed: 0.991889238357544
Processed 581 rows out of 1000 total sentences 6
Processed 582 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 915.31ms

-------Total time elapsed: 1.1202242374420166
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1145.26ms

-------Total time elapsed: 1.3484971523284912
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 636.47ms

-------Total time elapsed: 0.8400282859802246
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 737.13ms

-------Total time elapsed: 0.9413802623748779
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 837.86ms

-------Total time elapsed: 1.041949987411499
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 815.10ms

-------Total time elapsed: 1.0190699100494385
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 938.41ms

-------Total time elapsed: 1.143174648284912
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 940.10ms

-------Total time elapsed: 1.1443219184875488
----------sentence 8

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 688.23ms

-------Total time elapsed: 0.8908240795135498
----------sentence 9

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 838.82ms

-------Total time elapsed: 1.042351245880127
----------sentence 10

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1040.93ms

-------Total time elapsed: 1.2452163696289062
----------sentence 11
... [56 lines truncated] ...
-------Total time elapsed: 1.828125238418579
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 965.06ms

-------Total time elapsed: 1.1679351329803467
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 840.36ms

-------Total time elapsed: 1.0434975624084473
Processed 611 rows out of 1000 total sentences 4
Processed 612 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 814.21ms

-------Total time elapsed: 1.017491340637207
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 637.01ms

-------Total time elapsed: 0.8409936428070068
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 716.12ms

-------Total time elapsed: 0.918473482131958
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 739.01ms

-------Total time elapsed: 0.943720817565918
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 990.33ms

-------Total time elapsed: 1.1945805549621582
Processed 612 rows out of 1000 total sentences 5
Processed 613 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 889.81ms

-------Total time elapsed: 1.0938947200775146
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 940.36ms

-------Total time elapsed: 1.1441354751586914
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 890.35ms

-------Total time elapsed: 1.0941970348358154
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 737.33ms

-------Total time elapsed: 0.9412581920623779
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 735.51ms

-------Total time elapsed: 0.9407556056976318
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 886.86ms

-------Total time elapsed: 1.0942871570587158
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 812.65ms

-------Total time elapsed: 1.0162410736083984
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 738.43ms

-------Total time elapsed: 0.9414725303649902
----------sentence 8

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 661.48ms

-------Total time elapsed: 0.8647232055664062
----------sentence 9

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 737.04ms

-------Total time elapsed: 0.9410264492034912
Processed 613 rows out of 1000 total sentences 10
Processed 614 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 763.99ms

-------Total time elapsed: 0.9657065868377686
----------sentence 1

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 840.61ms

-------Total time elapsed: 1.0435028076171875
----------sentence 2

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 890.06ms

-------Total time elapsed: 1.0946776866912842
----------sentence 3

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 940.76ms

-------Total time elapsed: 1.1446607112884521
----------sentence 4

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 814.37ms

-------Total time elapsed: 1.016864538192749
----------sentence 5

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 840.02ms

-------Total time elapsed: 1.0431063175201416
----------sentence 6

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 688.85ms

-------Total time elapsed: 0.8926174640655518
----------sentence 7

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 787.82ms

-------Total time elapsed: 0.9897868633270264
----------sentence 8

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 788.40ms

-------Total time elapsed: 0.9917893409729004
----------sentence 9

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 866.08ms

-------Total time elapsed: 1.067413330078125
Processed 614 rows out of 1000 total sentences 10
Processed 615 rows out of 1000 ------------------
----------sentence 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 786.23ms

-------Total time elapsed: 0.9941246509552002
----------sentence 1
... [56 lines truncated] ...
-------Total time elapsed: 1.7242343425750732
----------sentence 3

ERROR:tornado.access:503 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1217.79ms

-------Total time elapsed: 4.756329536437988
----------sentence 4
-------Total time elapsed: 1.8275840282440186
----------sentence 5

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1143.61ms

-------Total time elapsed: 1.34621000289917
----------sentence 6
... [16 lines truncated] ...
-------Total time elapsed: 1.7253773212432861
----------sentence 4

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1138.65ms

-------Total time elapsed: 1.3449671268463135
----------sentence 5

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1321.33ms

-------Total time elapsed: 1.5230152606964111
Processed 627 rows out of 1000 total sentences 6
... [56 lines truncated] ...
-------Total time elapsed: 2.1809701919555664
----------sentence 4

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1066.88ms

-------Total time elapsed: 1.2698101997375488
----------sentence 5
... [2 lines truncated] ...
-------Total time elapsed: 3.347083568572998
----------sentence 7

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1216.25ms

-------Total time elapsed: 1.4211466312408447
----------sentence 8
... [56 lines truncated] ...
-------Total time elapsed: 3.5012454986572266
----------sentence 3

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1167.75ms

-------Total time elapsed: 1.3712172508239746
----------sentence 4
... [40 lines truncated] ...
-------Total time elapsed: 3.296978712081909
----------sentence 1

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1367.91ms

-------Total time elapsed: 1.5731525421142578
----------sentence 2
... [30 lines truncated] ...
Processed 662 rows out of 1000 ------------------
----------sentence 0

ERROR:tornado.access:503 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1547.52ms

-------Total time elapsed: 4.094294786453247
----------sentence 1
... [56 lines truncated] ...
-------Total time elapsed: 2.2088100910186768
----------sentence 1

In [21]:
#   'introduction_id': 68,
#   'sentence': '2) It can handle an input solution set with an arbitrary number of solutions (i.e., the number of solutions in the input solution set is not fixed).',

import pandas as pd
df_results = pd.DataFrame(results, columns=['df_id', 'introduction_id', 'sentence', 'label'])

df_results.head()

,df_id,introduction_id,sentence,label
0,2000,120,(1)\nWe propose an M-FSCIL that can more effec...,Occupying the Niche
1,2000,120,(2)\nMemory prompt is introduced to learn new ...,Establishing a Research Territory
2,2000,120,(3)\nWe propose a novel stimulation-based trai...,Establishing a Niche
3,2000,120,"(4)\nExperiments on MiniImageNet, CUB200, and ...",Occupying the Niche
4,2000,121,"In the area of process mining [1]}, we typical...",Establishing a Research Territory

In [22]:
results[0]

{'df_id': 1000,
 'introduction_id': 433,
 'sentence': 'Early on in the COVID-19 pandemic, UNESCO recognized that the “way the world is responding to this unprecedented global crisis will be part of history books.” UNESCO went on to say that “[m]emory institutions, including national archives ...are already recording the decisions and actions being made which will help future generations to understand the extent of the pandemic and its impact on societies,” and that “it is important, now more than ever, for memory institutions to become even more readily accessible to researchers, policymakers … and the community at large”\xa0[1]}.',
 'label': 'Establishing a Research Territory'}

In [23]:
df_results.shape

(1556, 4)

In [24]:
  !mkdir /content/drive/MyDrive/pfe/gemini-results/{chunk_id}/

mkdir: cannot create directory ‘/content/drive/MyDrive/pfe/gemini-results/0/’: No such file or directory

## 6 — Results Export
Collect results into a DataFrame and save as a partial CSV to Google Drive. `row_id_out` and `column_id_out` record resume checkpoints.

In [25]:
# prompt: if the : /content/drive/MyDrive/pfe/gemini-results/{chunk_id}/ directory do not exist create it

In [26]:
from google.colab import drive
drive.mount('/content/drive')

In [27]:
unique_introduction_ids = df_results['introduction_id'].unique()
row_id_out = len(unique_introduction_ids)
column_id_out = df_results.shape[0]

In [28]:
row_id_out,column_id_out

(73, 479)

In [29]:
  df_results.to_csv(f'/content/drive/MyDrive/pfe/gemini-results/{chunk_id}/partial_row_{411}-{0}.csv', index=False)